version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.18.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # - run: yarn install
      - run: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cd www && yarn test
      - run: sudo apt-get update && sudo apt-get install -y gettext-base
      - run: cd www && envsubst < ".env.ci" > ".env.production"
      - run: cd www && yarn build
      - persist_to_workspace:
          root: .
          paths:
            - www/public
  deploy-prod:
    docker:
      - image: circleci/node:10.18.1-stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: ls -l www/public
      - run:
          name: Install Firebase locally
          command: cd www && npm install --save-dev firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: cd www && ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN  --only hosting
  e2e-tests:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:10.18.1
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running E2E tests
          command: cd www && yarn ci:e2e
      - store_test_results:
          path: e2e-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - e2e-tests:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - e2e-tests
          filters:
            branches:
              only: master
